spring.application.name=cricketmatch_Yatin

server.port=8090

app.jwt.secret="yatin21"
app.jwt.expiration-ms=360000000   

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/cricketmatch
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Logging Configuration - Creates date-wise log files in 'logs' folder

logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.com.ds.app=INFO



